#!/usr/bin/env bash
#Sets nginx for listening to 80 port as in task 0 service (init) must say that nginx is not running ← for real
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
